plugins {
    id 'java'
}

repositories {
    mavenCentral()
}

dependencies {


    implementation 'org.slf4j:slf4j-api:2.0.7'
    implementation 'ch.qos.logback:logback-classic:1.5.13'
    testImplementation 'org.junit.jupiter:junit-jupiter:5.9.3'

}

test {
    useJUnitPlatform()
}

sourceSets {
    main {
        java { srcDirs = ['src'] }
        resources { srcDirs = ['resources'] }
    }
    test {
        java { srcDirs = ['test'] }
    }
}